image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-Dhttp.proxyHost=proxy.ensinfo.sciences.univ-nantes.prive -Dhttp.proxyPort=3128"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - 'mvn -Dhttp.proxyHost=proxy.ensinfo.sciences.univ-nantes.prive -Dhttp.proxyPort=3128 compile'

test:
  stage: test
  script:
    - 'mvn -Dhttp.proxyHost=proxy.ensinfo.sciences.univ-nantes.prive -Dhttp.proxyPort=3128 test'

deploy:
  stage: deploy
  script:
    - 'mvn -Dhttp.proxyHost=proxy.ensinfo.sciences.univ-nantes.prive -Dhttp.proxyPort=3128 deploy'
  only:
    - master