image: maven:3.6.1-jdk-8

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dhttp.proxyHost=proxy-serveur.univ-nantes.prive -Dhttp.proxyPort=3128"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository/
  key: "$CI_BUILD_REF_NAME"

before_script:
  - 'apt-get update -qq && apt-get install -y -qq graphviz rsync'
  

build:
  stage: build
  script:
    - 'mvn --settings ./.gitlab.maven.settings.xml $MAVEN_OPTS -e $MAVEN_CLI_OPTS compile'
  artifacts:
    paths:
      - target/
      - salut-common/target

test:
  stage: test
  script:
    - 'mvn --settings ./.gitlab.maven.settings.xml $MAVEN_OPTS test'
  artifacts:
    paths:
      - target/
      - salut-common/target

verify:
  stage: test
  script:
    - 'mvn --settings ./.gitlab.maven.settings.xml $MAVEN_OPTS verify'
  artifacts:
    paths:
      - target/
      - salut-common/target

pages:
  stage: deploy
  script:
  - 'mvn --settings .gitlab.maven.settings.xml $MAVEN_OPTS -e $MAVEN_CLI_OPTS site'
  - mkdir -p public/salut-common
  - rsync -r target/site/ public
  - rsync -r salut-common/target/site/ public/salut-common
  artifacts:
    paths:
    - public
  only:
  - master
