image: maven:latest

variables:
  MVN_OPTIONS: "-Dhttp.proxyHost=proxy.ensinfo.sciences.univ-nantes.prive -Dhttp.proxyPort=3128"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MVN_OPTIONS compile

test:
  stage: test
  script:
    - mvn $MVN_OPTIONS test

deploy:
  stage: deploy
  script:
    - mvn $MVN_OPTIONS deploy
  only:
    - master