image: maven:3.6.1-jdk-8

variables:
  MAVEN_OPTS: "-Dhttps.proxyHost=proxy-serveur.univ-nantes.prive -Dhttps.proxyPort=3128 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/

before_script:
  - 'apt-get update -qq && apt-get install -y -qq graphviz' 
  

build:
  stage: build
  script:
    - 'mvn --settings ./.gitlab.maven.settings.xml $MAVEN_OPTS -e $MAVEN_CLI_OPTS compile'

test:
  stage: test
  script:
    - 'mvn --settings ./.gitlab.maven.settings.xml $MAVEN_OPTS test'

#deploy:
#  stage: deploy
#  script:
#    - 'mvn $MAVEN_OPTS deploy'
#  only:
#    - master

pages:
  stage: deploy
  script:
  - 'mvn -Dhttps.proxyHost=proxy-serveur.univ-nantes.prive -Dhttps.proxyPort=3128 --settings .gitlab.maven.settings.xml clean site'
  - 'mv target/site/* ./public/'
  artifacts:
    paths:
    - public
  only:
  - master
